# Generated by Django 2.2.1 on 2019-09-12 08:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='验证码')),
                ('email', models.EmailField(max_length=50, verbose_name='邮箱')),
                ('send_type', models.CharField(choices=[('register', '注册'), ('forget', '找回密码')], max_length=10, verbose_name='验证码类型')),
                ('send_time', models.DateTimeField(default=django.utils.datetime_safe.datetime.now, verbose_name='发送时间')),
            ],
        ),
        migrations.CreateModel(
            name='Login_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('ip', models.CharField(max_length=30)),
                ('area', models.CharField(max_length=30)),
                ('time', models.DateTimeField()),
                ('operat', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='新闻标题')),
                ('header', models.CharField(max_length=50, verbose_name='主题简介')),
                ('text', models.TextField(verbose_name='内容')),
                ('readcount', models.IntegerField(verbose_name='阅读量')),
            ],
            options={
                'verbose_name': '添加新闻',
                'verbose_name_plural': '添加新闻',
                'db_table': 'News',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='轮播图标题')),
                ('href', models.CharField(max_length=150, verbose_name='图片广告链接')),
                ('src', models.ImageField(upload_to='static/img/banner/', verbose_name='图片')),
                ('position', models.IntegerField(choices=[(1, 'new'), (2, 'old')], default=1, verbose_name='顺序')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
                'db_table': 'Photo',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='用户id')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='邮箱')),
                ('passwd', models.CharField(max_length=100, verbose_name='密码')),
                ('is_active', models.BooleanField(default=False)),
                ('phone', models.CharField(default='null', max_length=20)),
                ('headImg', models.ImageField(upload_to='img/headImg', verbose_name='用户头像')),
                ('name', models.CharField(default=models.EmailField(max_length=50, unique=True, verbose_name='邮箱'), max_length=50, verbose_name='用户名')),
                ('gender', models.IntegerField(choices=[(0, 'null'), (1, 'Male'), (2, 'Female')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=30, verbose_name='商品名称')),
                ('out_trade_no', models.CharField(max_length=30, verbose_name='订单号')),
                ('foods_price', models.FloatField(max_length=10, verbose_name='单价')),
                ('amount', models.IntegerField(verbose_name='商品总数')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.User', verbose_name='用户id')),
            ],
        ),
    ]
