# Generated by Django 2.2.1 on 2019-09-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foods_name', models.CharField(max_length=30, verbose_name='商品名称')),
                ('foods_price', models.FloatField(verbose_name='单价')),
                ('foods_img', models.ImageField(upload_to='static/foodsimg/', verbose_name='商品图片')),
                ('foods_mess', models.CharField(max_length=100, verbose_name='商品信息')),
            ],
            options={
                'verbose_name': '添加商品信息',
                'db_table': 'Foods',
            },
        ),
    ]
