# Generated by Django 2.2.1 on 2019-09-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_foods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='用户id'),
        ),
    ]
